# Generated by Django 4.0.2 on 2022-02-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='hybrid',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
