# Generated by Django 4.0.2 on 2022-02-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_app', '0002_laptop_hybrid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='flash_storage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='hdd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='hybrid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ssd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='stock_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='weight',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
