# Generated by Django 4.0.2 on 2022-02-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_app', '0004_order_total_price_alter_laptop_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.FloatField()),
                ('total_items', models.IntegerField()),
                ('unique_customers', models.CharField(max_length=526)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('review_title', models.CharField(max_length=128)),
                ('review_content', models.CharField(max_length=526)),
                ('laptop_grade', models.CharField(choices=[('1', '1 STARS'), ('2', '2 STARS'), ('3', '3 STARS'), ('4', '4 STARS'), ('5', '5 STARS')], max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='laptop_app.customer')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='laptop_app.laptop')),
            ],
        ),
    ]
