# Generated by Django 4.0.2 on 2022-02-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_app', '0006_alter_reviews_laptop_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='laptop_grade',
            field=models.IntegerField(),
        ),
    ]
